
from wx import NewIdRef as wxNewIdRef

from umldiagrammer.UIAction import UIAction


class UIIdentifiers:

    [
        ID_FILE_MENU_NEW_PROJECT,
        ID_FILE_MENU_OPEN_XML_PROJECT,
        ID_MENU_FILE_IMPORT,
        ID_MENU_FILE_EXPORT,
        ID_MENU_FILE,
        ID_MENU_FILE_PRINT_SETUP, ID_MENU_FILE_PRINT_PREVIEW, ID_MENU_FILE_PRINT,
        ID_MENU_FILE_MANAGE_FILE_HISTORY,
        ID_MENU_FILE_PROJECT_CLOSE,
        ID_MENU_FILE_NEW_CLASS_DIAGRAM, ID_MENU_FILE_NEW_SEQUENCE_DIAGRAM,
        ID_MENU_FILE_NEW_USECASE_DIAGRAM,
        ID_MENU_FILE_REMOVE_DIAGRAM,

        ID_MENU_EDIT_ADD_PYUT_DIAGRAM, ID_MENU_EDIT_ADD_OGL_DIAGRAM,
        ID_MENU_GRAPHIC_ERROR_VIEW, ID_MENU_TEXT_ERROR_VIEW, ID_MENU_RAISE_ERROR_VIEW,
        ID_MENU_EDIT_SHOW_TOOLBAR,

        ID_MENU_HELP_VERSION, ID_MENU_HELP_WEB, ID_MENU_HELP_LOGGING_CONTROL, ID_MENU_HELP_DEBUG_EVENT_ENGINE,

        ID_SD_INSTANCE, ID_SD_MESSAGE,
        ID_ARROW, ID_CLASS,
        ID_NOTE, ID_ACTOR,
        ID_USECASE, ID_REL_NOTE, ID_TEXT,
        ID_RELATIONSHIP_INHERITANCE, ID_RELATIONSHIP_REALIZATION, ID_RELATIONSHIP_COMPOSITION, ID_RELATIONSHIP_AGGREGATION, ID_RELATIONSHIP_ASSOCIATION,

    ] = wxNewIdRef(38)

    ACTIONS = {
        ID_ARROW:                    UIAction.SELECTOR,
        ID_CLASS:                    UIAction.NEW_CLASS,
        ID_NOTE:                     UIAction.NEW_NOTE,
        ID_RELATIONSHIP_INHERITANCE: UIAction.NEW_INHERIT_LINK,
        ID_RELATIONSHIP_REALIZATION: UIAction.NEW_IMPLEMENT_LINK,

        ID_RELATIONSHIP_COMPOSITION: UIAction.NEW_COMPOSITION_LINK,
        ID_RELATIONSHIP_AGGREGATION: UIAction.NEW_AGGREGATION_LINK,
        ID_RELATIONSHIP_ASSOCIATION: UIAction.NEW_ASSOCIATION_LINK,
        ID_REL_NOTE:                 UIAction.NEW_NOTE_LINK,
        ID_ACTOR:                    UIAction.NEW_ACTOR,
        ID_TEXT:                     UIAction.NEW_TEXT,
        ID_USECASE:                  UIAction.NEW_USECASE,
        ID_SD_INSTANCE:              UIAction.NEW_SD_INSTANCE,
        ID_SD_MESSAGE:               UIAction.NEW_SD_MESSAGE,
    }
