
from wx import NewIdRef as wxNewIdRef

class UIIdentifiers:

    [
        ID_FILE_MENU_NEW_PROJECT,
        ID_FILE_MENU_OPEN_XML_PROJECT,
        ID_FILE_MENU_OPEN_PROJECT,
        ID_MENU_FILE_PROJECT_CLOSE,
        ID_MENU_FILE_PROJECT_SAVE,
        ID_MENU_FILE_IMPORT,
        ID_MENU_FILE_EXPORT,

        ID_MENU_FILE_PRINT_SETUP, ID_MENU_FILE_PRINT_PREVIEW, ID_MENU_FILE_PRINT,
        ID_MENU_FILE_MANAGE_FILE_HISTORY,
        ID_MENU_FILE_NEW_CLASS_DIAGRAM, ID_MENU_FILE_NEW_SEQUENCE_DIAGRAM,
        ID_MENU_FILE_NEW_USECASE_DIAGRAM,
        ID_MENU_FILE_REMOVE_DIAGRAM,

        ID_MENU_EDIT_ADD_PYUT_DIAGRAM,
        ID_MENU_EDIT_ADD_OGL_DIAGRAM,
        ID_MENU_GRAPHIC_ERROR_VIEW, ID_MENU_TEXT_ERROR_VIEW, ID_MENU_RAISE_ERROR_VIEW,
        ID_MENU_EDIT_SHOW_TOOLBAR,

        ID_MENU_HELP_VERSION, ID_MENU_HELP_WEB, ID_MENU_HELP_LOGGING_CONTROL, ID_MENU_HELP_PUB_SUB_ENGINE,

        ID_SD_INSTANCE, ID_SD_MESSAGE,
        ID_ARROW, ID_CLASS,
        ID_NOTE, ID_ACTOR,
        ID_USECASE,
        ID_TEXT,
        ID_RELATIONSHIP_NOTE, ID_RELATIONSHIP_INHERITANCE, ID_RELATIONSHIP_REALIZATION, ID_RELATIONSHIP_COMPOSITION, ID_RELATIONSHIP_AGGREGATION, ID_RELATIONSHIP_ASSOCIATION,

    ] = wxNewIdRef(39)
