

from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from umldiagrammer.UniqueNameGenerator import NameList
from umldiagrammer.UniqueNameGenerator import createUniqueName
from umldiagrammer.UniqueNameGenerator import DISCRIMINATOR_END
from umldiagrammer.UniqueNameGenerator import DISCRIMINATOR_START

NAME_TO_CHECK:   str = 'Class Diagram'

class TestUniqueNameGenerator(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 13 November 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testNameAlreadyUnique(self):

        uniqueName: str = createUniqueName(nameToCheck=NAME_TO_CHECK, names=NameList([]))

        self.assertEqual(NAME_TO_CHECK, uniqueName, 'This should be unique since list is empty')

    def testNameAlreadyUniqueWithNameList(self):

        names: NameList = NameList([
            'Sequence Diagram',
            'Use Case Diagram'
        ])
        uniqueName: str = createUniqueName(nameToCheck=NAME_TO_CHECK, names=names)

        self.assertEqual(NAME_TO_CHECK, uniqueName, 'This should be unique since list is empty')

    def testNameNotUniqueIterateOnce(self):

        names: NameList = NameList([
            NAME_TO_CHECK,
            'Sequence Diagram',
            'Use Case Diagram'
        ])
        uniqueName: str = createUniqueName(nameToCheck=NAME_TO_CHECK, names=names)

        expectedUniqueName: str = f'{NAME_TO_CHECK}{DISCRIMINATOR_START}1{DISCRIMINATOR_END}'
        self.assertEqual(expectedUniqueName, uniqueName, 'This should be unique since list is empty')

    def testNameNotUniqueIterateMultipleTimes(self):

        names: NameList = NameList([
            f'{NAME_TO_CHECK}',
            f'{NAME_TO_CHECK}{DISCRIMINATOR_START}1{DISCRIMINATOR_END}',
            f'{NAME_TO_CHECK}{DISCRIMINATOR_START}2{DISCRIMINATOR_END}',
            f'{NAME_TO_CHECK}{DISCRIMINATOR_START}3{DISCRIMINATOR_END}',
            f'{NAME_TO_CHECK}{DISCRIMINATOR_START}4{DISCRIMINATOR_END}',
            'Sequence Diagram',
            'Use Case Diagram'
        ])
        uniqueName: str = createUniqueName(nameToCheck=NAME_TO_CHECK, names=names)

        expectedUniqueName: str = f'{NAME_TO_CHECK}(5)'
        self.assertEqual(expectedUniqueName, uniqueName, 'This should be unique since list is empty')

def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestUniqueNameGenerator))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
